openapi: 3.0.0
info:
  title: BE Mini Project 5 (Microservice)
  version: 1.0.0
servers:
  - url: http://localhost:5000
    variables:
      base_url:
        default: localhost:5000
        description: local
tags:
  - name: Orders
paths:
  /:
    get:
      tags:
        - default
      summary: Ping
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ping"
  /orders:
    post:
      tags:
        - Orders
      summary: Order a product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
                - user_id
              properties:
                product_id:
                  type: number
                quantity:
                  type: number
                user_id:
                  type: number
              example:
                product_id: 1
                quantity: 3
                user_id: 1
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Failed response
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                  status:
                    type: number
                  message:
                    type: string
                example:
                  success: false
                  status: 200
                  message: "Out of stock"
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                  status:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
  /orders/kafka:
    post:
      tags:
        - Orders
      summary: Order a product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
                - user_id
              properties:
                product_id:
                  type: number
                quantity:
                  type: number
                user_id:
                  type: number
              example:
                product_id: 1
                quantity: 3
                user_id: 1
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Failed response
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                  status:
                    type: number
                  message:
                    type: string
                example:
                  success: false
                  status: 200
                  message: "Out of stock"
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                  status:
                    type: number
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
  
components:
  schemas:
    Ping:
      properties:
        success:
          type: boolean
        status:
          type: number
        message:
          type: string
      example:
        success: true
        status: 200
        message: "Orders API"

    Error:
      properties:
        success:
          type: boolean
        status:
          type: boolean
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  responses:
    Unauthorized:
      description: Unauthorized response
      content:
        application/json:
          schema:
            properties:
              success:
                type: boolean
              message:
                type: string
            example:
              success: false
              message: "invalid signature"
    Forbidden:
      description: Forbidden response
      content:
        application/json:
          schema:
            properties:
              success:
                type: boolean
              message:
                type: string
            example:
              success: false
              message: "You are not allowed"
